---

version: 2

updates:
  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Set update schedule for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
