---

name: ci
on:
  push:
    # branches:
    #   - main

jobs:
  build:
    strategy:
      matrix:
        data:
          - package: ansible-core
          - package: ansible-core
            version: 2.16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Print docker version information'
        run: |
          docker --version
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: 'GetBuildTime'
      #   run: |
      #     echo "NOW=$(TZ='Europe/Berlin' date --rfc-3339=seconds)" >> $BUILD_TIME
      - name: 'Set Docker meta'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: thehedhly/${{ matrix.data.package }}
          labels: |
            org.opencontainers.image.version=${{ matrix.data.version }}
          tags: |
            type=raw,value=${{ matrix.data.version == '' && 'latest' || matrix.data.version }}
      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          push: true
          # tags: thehedhly/ansible:latest
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ANSIBLE_INSTALL_REFS=${{ matrix.data.version == '' && matrix.data.package || format('{0}=={1}',matrix.data.package,matrix.data.version) }}

# ANSIBLE_INSTALL_REFS=${{ matrix.data.package }}==${{ matrix.data.version }}
